     apiVersion: k3d.io/v1alpha5
     kind: Simple
     metadata:
       name: study-app-cluster
     servers: 1
     agents: 1
     ports:
       - port: 22111:22111
         nodeFilters:
           - loadbalancer
       - port: 22112:22112
         nodeFilters:
           - loadbalancer
     options:
       k3s:
         extraArgs:
           - arg: --disable=traefik
             nodeFilters:
               - server:*
